//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingPlanner.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string UserName { get; set; }
        public int AccessLevel { get; set; }
    
        public virtual User User { get; set; }
    }
}
